#!/bin/bash
python3 build.py
[ "$?" == "0" ] || exit 1
echo "wherethemag.amasud.xyz" > build/CNAME
pushd build > /dev/null
git init
git remote add origin https://github.com/lugocorp/where.git
ssh -T git@github.com
if [ "$?" -ne "255" ]; then
  git remote set-url origin git@github.com:lugocorp/where.git
fi
git add .
git commit -m "Update on $(date)"
git push -f origin master:gh-pages
popd > /dev/null
