#!/bin/bash
python3 build.py
[ "$?" == "0" ] || exit 1
echo "wherethemag.com" > build/CNAME
pushd build > /dev/null
git init
git remote add origin https://github.com/lugocorp/where.git
git add .
git commit -m "Update on $(date)"
git push -f origin master:gh-pages
popd > /dev/null
